document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <title></title>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' media=\'screen\' href=\'css/clearstyle.css\'>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' media=\'screen\' href=\'css/footer.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div class=\'footer\'>");
document.writeln("        <p>Copyright@Melody 2019</p>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");